### ISSUE TITLE
What is the difference between jni_all.h and jni.h

### ISSUE THREAD

**Issue by 4val0v** [Jinmo/headers#1]
What is the difference [jni.h (this repo)](https://github.com/Jinmo/headers/blob/master/jni.h) and [jni_all.h (gist)](https://gist.github.com/Jinmo/048776db75067dcd6c57f1154e65b868)?
Which to use?

**Comment by Jinmo** [comment]
Actually I forgot the difference so compared them; it seems like jni_all.h has more detail, so I suggest using it. Thank you! I'm going to update this repo now.
